/*
 * Camel Api Route test generated by camel-api-component-maven-plugin
 * Generated on: Mon May 28 16:47:45 CEST 2018
 */
package org.apache.camel.component.fhir;

import java.util.HashMap;
import java.util.Map;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.component.fhir.internal.FhirApiCollection;
import org.apache.camel.component.fhir.internal.FhirOperationApiMethod;
import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Test class for {@link org.apache.camel.component.fhir.api.FhirOperation} APIs.
 * The class source won't be generated again if the generator MOJO finds it under src/test/java.
 */
public class FhirOperationIntegrationTest extends AbstractFhirTestSupport {

    private static final Logger LOG = LoggerFactory.getLogger(FhirOperationIntegrationTest.class);
    private static final String PATH_PREFIX = FhirApiCollection.getCollection().getApiName(FhirOperationApiMethod.class).getName();

    // TODO provide parameter values for messageBundle
    @Ignore
    @Test
    public void testMessageBundle() throws Exception {
        final Map<String, Object> headers = new HashMap<String, Object>();
        // parameter type is org.hl7.fhir.instance.model.api.IBaseBundle
        headers.put("CamelFhir.theMsgBundle", null);
        // parameter type is Class
        headers.put("CamelFhir.theResponseClass", null);

        final org.hl7.fhir.instance.model.api.IBaseResource result = requestBodyAndHeaders("direct://MESSAGEBUNDLE", null, headers);

        assertNotNull("messageBundle result", result);
        LOG.debug("messageBundle: " + result);
    }

    @Override
    protected RouteBuilder createRouteBuilder() throws Exception {
        return new RouteBuilder() {
            public void configure() {
                // test route for messageBundle
                from("direct://MESSAGEBUNDLE")
                    .to("fhir://" + PATH_PREFIX + "/messageBundle");

            }
        };
    }
}
