/*
 * Camel Api Route test generated by camel-api-component-maven-plugin
 * Generated on: Mon May 28 16:47:45 CEST 2018
 */
package org.apache.camel.component.fhir;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.component.fhir.internal.FhirApiCollection;
import org.apache.camel.component.fhir.internal.FhirTransactionApiMethod;
import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Test class for {@link org.apache.camel.component.fhir.api.FhirTransaction} APIs.
 * TODO Move the file to src/test/java, populate parameter values, and remove @Ignore annotations.
 * The class source won't be generated again if the generator MOJO finds it under src/test/java.
 */
public class FhirTransactionIntegrationTest extends AbstractFhirTestSupport {

    private static final Logger LOG = LoggerFactory.getLogger(FhirTransactionIntegrationTest.class);
    private static final String PATH_PREFIX = FhirApiCollection.getCollection().getApiName(FhirTransactionApiMethod.class).getName();

    // TODO provide parameter values for withBundle
    @Ignore
    @Test
    public void testWithBundle() throws Exception {
        // using org.hl7.fhir.instance.model.api.IBaseBundle message body for single parameter "bundle"
        final org.hl7.fhir.instance.model.api.IBaseBundle result = requestBody("direct://WITHBUNDLE", null);

        assertNotNull("withBundle result", result);
        LOG.debug("withBundle: " + result);
    }

    // TODO provide parameter values for withBundle
    @Ignore
    @Test
    public void testWithBundle_1() throws Exception {
        // using String message body for single parameter "sBundle"
        final String result = requestBody("direct://WITHBUNDLE_1", null);

        assertNotNull("withBundle result", result);
        LOG.debug("withBundle: " + result);
    }

    // TODO provide parameter values for withResources
    @Ignore
    @Test
    public void testWithResources() throws Exception {
        // using java.util.List message body for single parameter "resources"
        final java.util.List result = requestBody("direct://WITHRESOURCES", null);

        assertNotNull("withResources result", result);
        LOG.debug("withResources: " + result);
    }

    @Override
    protected RouteBuilder createRouteBuilder() throws Exception {
        return new RouteBuilder() {
            public void configure() {
                // test route for withBundle
                from("direct://WITHBUNDLE")
                    .to("fhir://" + PATH_PREFIX + "/withBundle?inBody=bundle");

                // test route for withBundle
                from("direct://WITHBUNDLE_1")
                    .to("fhir://" + PATH_PREFIX + "/withBundle?inBody=sBundle");

                // test route for withResources
                from("direct://WITHRESOURCES")
                    .to("fhir://" + PATH_PREFIX + "/withResources?inBody=resources");

            }
        };
    }
}
