/*
 * Camel Api Route test generated by camel-api-component-maven-plugin
 * Generated on: Mon May 28 16:47:45 CEST 2018
 */
package org.apache.camel.component.fhir;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.component.fhir.internal.FhirApiCollection;
import org.apache.camel.component.fhir.internal.FhirValidateApiMethod;
import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Test class for {@link org.apache.camel.component.fhir.api.FhirValidate} APIs.
 * TODO Move the file to src/test/java, populate parameter values, and remove @Ignore annotations.
 * The class source won't be generated again if the generator MOJO finds it under src/test/java.
 */
public class FhirValidateIntegrationTest extends AbstractFhirTestSupport {

    private static final Logger LOG = LoggerFactory.getLogger(FhirValidateIntegrationTest.class);
    private static final String PATH_PREFIX = FhirApiCollection.getCollection().getApiName(FhirValidateApiMethod.class).getName();

    // TODO provide parameter values for resource
    @Ignore
    @Test
    public void testResource() throws Exception {
        // using org.hl7.fhir.instance.model.api.IBaseResource message body for single parameter "resource"
        final ca.uhn.fhir.rest.api.MethodOutcome result = requestBody("direct://RESOURCE", null);

        assertNotNull("resource result", result);
        LOG.debug("resource: " + result);
    }

    // TODO provide parameter values for resource
    @Ignore
    @Test
    public void testResource_1() throws Exception {
        // using String message body for single parameter "sResource"
        final ca.uhn.fhir.rest.api.MethodOutcome result = requestBody("direct://RESOURCE_1", null);

        assertNotNull("resource result", result);
        LOG.debug("resource: " + result);
    }

    @Override
    protected RouteBuilder createRouteBuilder() throws Exception {
        return new RouteBuilder() {
            public void configure() {
                // test route for resource
                from("direct://RESOURCE")
                    .to("fhir://" + PATH_PREFIX + "/resource?inBody=resource");

                // test route for resource
                from("direct://RESOURCE_1")
                    .to("fhir://" + PATH_PREFIX + "/resource?inBody=sResource");

            }
        };
    }
}
